### ISSUE TITLE
Swarmlet assumes /root/.ssh/authorized_keys for access

### ISSUE THREAD

**Issue by decentral1se** [swarmlet/swarmlet#15]
```bash
cat /root/.ssh/authorized_keys | ts "$SSH_OPTIONS" > $USER_ROOT/.ssh/authorized_keys
```

This isn't always the case? 

Perhaps it would be better to detect the current users and take that authorized_keys file? In the dokku world, we have that initial install screen where you can add a public key. Furthermore, there is the `dokku ssh-key add` command-line interface. I am not sure which suits Swarmlet better to do ;)

**Comment by woudsma** [comment]
I agree 😉 
As you've seen the project is barely version 0.1, there are lots of improvements to make.
This is one of those things. I'm still thinking about what the best solution is.

I kind of want to avoid that screen where you have to copy-paste your key, like Dokku does. Because it usually filled in a public key automatically, I sometimes forgot about it, and my key + access to the server was exposed for a while.

I'm also thinking about a installation wizard kind of thing, where you can select some options and define which key to use. But I'd really like to keep the option of a headless installation without wizard.

**Comment by decentral1se** [comment]
Sure, good points.

I guess my proposal is then to take the current `$USER`s key. If you're running under root then it is the same, if not, then its yours. We can make this clear in the documentation, I guess. The current user always has a valid ssh key setup because they're already inside the machine.

CLI wizard would be excellent. I am not sure if that is easy under bash? 

I suppose some `read` expertise is required there :)

**Comment by woudsma** [comment]
Sure, a CLI wizard is actually quite fun to implement in bash :)
I'll have to search my projects for some nice snippets.

One thing to keep in mind is the order of installation, preferably the wizard would start as soon as you execute the install script, not after installation of dependencies, etc. Installation takes a minute or two so you might forget input is needed later on.

I'm liking the idea of using the `$USER`'s key, but I'm not completely sure that breaks some functionality. I've deliberately avoided using `sudo` throughout Swarmlet, so I guess we'd have to test if everything still installs/works if a user isn't a `sudoer`. If that works I'm all for this solution!

**Comment by awojtczyk** [comment]
Right now, if we are aiming to use the root, I've added creation the root  key if it doesn't exist.

**Comment by woudsma** [comment]
I just pushed pushed some changes from the develop branch into master, the path to `authorized_keys` is now read from a variable. We could incorporate this into a possible CLI wizard (interactive installation).
https://github.com/swarmlet/swarmlet/blob/5dbf911281aba5380d5b5e46816d0f8846d066f8/src/config#L18
