### ISSUE TITLE
Error when performing git push swarm master

### ISSUE THREAD

**Issue by orange888** [swarmlet/swarmlet#46]
I am following the demo video.
I noticed the installation created a new user "git"
However, the installation video is configuring ssh's "swarm" as "root"

When I am performing git push, am I supposed to push to user "root" or "git"?

Thanks.

**Comment by woudsma** [comment]
Hi, thanks for your interest in the project!

The Swarmlet installer creates a `git` user, this user manages your project repositories that you've pushed to the swarm, and runs the deployer service after receiving your repo's.

You should use `git@<remote>:<app-name>` as the swarm git remote. Examples:
```bash
git remote add swarm git@swarm:my-app  # see below how to use this syntax
git remote add swarm git@123.12.21.213:my-app  # using an ip address
git remote add swarm git@mydomain.com:my-app  # mydomain.com should point to the server ip in this case

# I'm calling the remote `swarm` in these examples, but you can change this to whatever you like of course

# Finally
git add . && git commit -m 'intial`
git push swarm master
```

Setting up your SSH config:
Edit (or create) the `~/.ssh/config` file locally.
```
Host *
	Port 22
	UseKeychain yes

Host swarm
	HostName 123.12.21.213
	User root
	IdentityFile ~/.ssh/id_rsa_swarm  # this is optional, only use if you use a custom SSH key for access to your swarm

```

Now `ssh root@123.12.21.213` becomes `ssh swarm`! 👍

**Comment by woudsma** [comment]
Update: The username and password shown in the video can be used to login to the swarm registry and the included and optional services dashboards, like Traefik, Consul, Matomo, Swarmpit, Portainer, Swarmprom, Grafana, etc.

These will be accessible if you point a domain to your server and configure the domain in the initial Swarmlet installation. They're hosted on these subdomains by default:
https://registry.yourdomain.com
https://traefik.yourdomain.com
https://consul.yourdomain.com
https://matomo.yourdomain.com
https://swarmpit.yourdomain.com
https://portainer.yourdomain.com
https://swarmprom.yourdomain.com
Etc. 😉

**Comment by orange888** [comment]
Thanks. When we are adding git remote and pushing to the remote

```
git remote add swarm git@swarm:my-app  
git push swarm master
```

Are we pushing through user **root** or **git**?
What I don't understand is this "git" user, how does it authenticate with the server when the ssh server config is all about root?

**Comment by orange888** [comment]
Nevermind, I think I got it.

**Comment by woudsma** [comment]
We're pushing through the `git` user :)
The reason we are root during installation is because we need permissions to install all dependencies and to configure the `git` user. (the username could be anything btw, but I've chosen for `git`).

You can switch to the git user when logged into the server as root using `su git` (and exit with `exit`), but the git user has limited privileges. If you try to SSH into the server as `git`, that will fail because the SSH command doesn't allow a PTY.
```bash
ssh git@swarm
$ PTY allocation request failed on channel 0
$ Connection to 188.166.74.238 closed.
```
```bash
# Other users can log in as usual
ssh someuser@swarm
ssh root@swarm  # or: ssh swarm
```

---

This is what happens during installation.
By prepending a SSH command before the `GIT_USER_ROOT/.ssh/authorized_keys` file, the SSH command will run on every login attempt on the git account. It tries to execute `git-shell`, which fails if it isn't a valid git command. You can just `git push` or `git clone` a repository like any git provider. Try pulling Matomo for example using `git clone git@swarm:matomo` or `git clone git@swarm:my-app`.


This is configured here:
https://github.com/swarmlet/swarmlet/blob/da4c65241eb12197267b36f9e65a02ec225bc304/src/lib/sshcommand#L3-L14

https://github.com/swarmlet/swarmlet/blob/da4c65241eb12197267b36f9e65a02ec225bc304/src/constants#L30

https://github.com/swarmlet/swarmlet/blob/da4c65241eb12197267b36f9e65a02ec225bc304/src/lib/functions#L103-L107

https://github.com/swarmlet/swarmlet/blob/da4c65241eb12197267b36f9e65a02ec225bc304/src/lib/functions#L110-L115

**Comment by arseniybanayev** [comment]
Hi there @woudsma - I love the framework but the git user is not auto-creating the repository as the sshcommand file above would suggest. First, I had to ssh to the server as root and set a password for the git user, because `git push [swarm main]` isn't happy with an empty password. Now at least I can authenticate when doing `git push swarm main`, but now I get `xyz does not appear to be a git repository. Could not read from remote repository.` And when I `ssh swarm` and `su git`, I only see `deployer.git` and `registry.git` in `~/repo`.

**Comment by awojtczyk** [comment]
@arseniybanayev please copy contents of root authorized_hosts file to git user and try again.

**Comment by arseniybanayev** [comment]
@awojtczyk thanks, that was a silly oversight from me! Now, though, the repository I'm trying to `git push` is still not auto-created. I still get:

```
fatal: 'xyz' does not appear to be a git repository
fatal: Could not read from remote repository.
```

**Comment by awojtczyk** [comment]
Each repository need to be created by the deployer.

**Comment by awojtczyk** [comment]
@arseniybanayev how does your .ssh/config file look like?

Also, what is the output of the  ssh -T git@YOURHOST ?

**Comment by arseniybanayev** [comment]
But in [this section](https://swarmlet.dev/docs/getting-started/ssh-key-setup#adding-a-git-remote) of the docs, it says:

> If a project doesn't exist already, a new repo will be created on the swarm named <project-name>.

Also, as user `git `I tried manually running the commands in the `sshcommand` file copied by @woudsma a few comments ago, but that didn't help. Maybe I'm missing a step that registers the bare repository with the git service on the swarmlet server somehow?
```
git init --bare ~/repo/xyz.git
cp ~/repo/deployer.git/hooks/post-receive ~/repo/xyz.git/hooks/
chown -R git:git~/repo/xyz.git
```

**Comment by arseniybanayev** [comment]
> @arseniybanayev how does your .ssh/config file look like?
```
Host *
        Port 22
        IgnoreUnknown UseKeychain
        UseKeychain yes

Host swarm
        HostName 167.99.144.75
        User root
        IdentityFile ~/.ssh/id_rsa_swarm
```

> Also, what is the output of the ssh -T git@YOURHOST ?
```
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-121-generic x86_64)
...
```

**Comment by awojtczyk** [comment]
@arseniybanayev 
So now, the very first steps from https://swarmlet.dev/docs/getting-started/deploying-applications should work for you.
Would you try and paste me the logs in case of failure?

Please note that master could be changed to main recently.

**Comment by ruanbekker** [comment]
I am experiencing the same issue, and done the steps above and this is my output:

```
# ssh config
Host swarmlet
    HostName apps.domain.com
    User root
    IdentityFile ~/.ssh/swarmlet
```

files in the `my-app` dir:

```
$ ls
Dockerfile         app.py             docker-compose.yml requirements.txt
```

after running:

```
git init
git remote add origin git@swarmlet:my-app
git add .
git commit -m 'initial'
```

my git config:

```
cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@swarmlet:my-app
	fetch = +refs/heads/*:refs/remotes/origin/*
```

but when pushing:

```
$ git push origin master
Warning: Permanently added 'apps.xxxx.xxxx,95.x.x.x' (ECDSA) to the list of known hosts.
fatal: 'my-app' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I can ssh as root and git:

```
$ ssh git@swarmlet
Warning: Permanently added 'apps.xxxxx.xxxxxx,95.x.x.x' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-73-generic x86_64)

git@swarmlet:~$
```

and on the server I cant see the directories being created:

```
$ ls -lah /mnt/gfs/git/{repo,data}/ | grep my-app | wc -l
0
```

I absolutely love your project, so I am happy to contribute, just looking for some pointers.
