### ISSUE TITLE
Does Swarmlet handle high availability gracefully when using with volume?

### ISSUE THREAD

**Issue by orange888** [swarmlet/swarmlet#47]
Does Swarmlet handle high availability gracefully when using with volume?
If you have worker and manager nodes, is it possible to setup volume such that a node (has app using volume) can go down without any issue?

**Comment by woudsma** [comment]
As of right now, volumes are created using the the default `local` storage driver. Actually there is only one shared volume created: `git-data`. All other volumes are defined in their own project `docker-compose.yml` file.

This is the only volume created during installation:
```bash
docker volume create --driver "local" -o o=bind -o type=none -o device=/home/git git-data
```

I was looking into distributed volumes, but didn't find a nice solution so far. Any ideas or tips are most welcome!

The volume data has to be saved on **some** disk.  
I'm not sure if replicating a volume across all nodes is a good idea but it would probably be most the simplest but inefficient way.

Another option would be to use a cloud storage provider such as AWS or DigitalOcean (or anything that https://rclone.org/#providers supports for example). That adds some more complexity for the user, it would be nice to keep things simple and optional. Definitely something to look into though, `rclone` makes these things relatively easy.

The final option I can think of, is running your own storage server inside (and/or outside) the swarm. Like a NAS. This would require joining a dedicated worker node, e.g. `swarm-worker-storage-1` to the swarm. But then the availability of the volume data is as stable as the storage server is. But I guess that's the problem with all solutions.

The most redundant way would probably be to continuously sync the `git-data` volume across all manager nodes, disk usage shouldn't be a problem right away since the `git-data` volume only contains repositories + repo content. This approach is not implemented yet.
Volumes created by the user should be easily configurable, maybe we can do something like the installation wizard / dialogs when creating a volume with e.g. `swarmlet volume create`.

If you feel to help out, or if you've built something yourself on top of Swarmlet, please let me know or create a PR! They are most welcome 👍 I'll add this to v0.3

All thoughts / feedback / suggestions welcome!

**Comment by woudsma** [comment]
This issue would be solved when https://github.com/swarmlet/swarmlet/issues/53 is finished

**Comment by woudsma** [comment]
Closing this because https://github.com/swarmlet/swarmlet/issues/72 is almost done 🙂
