### ISSUE TITLE
Installation Failure using DietPi: 404 Not Found

### ISSUE THREAD

**Issue by TrikkStar** [swarmlet/swarmlet#69]
Attempted to run the interactive installation on an RPi 3 running DietPi v6.32.2 and after finishing confirming all the options the installation failed with the following output:

> =====> Installing Swarmlet
> -----> Installing required packages
> -----> Cloning https://github.com/swarmlet/swarmlet.git
> -----> Swarmlet is already installed, updating
> -----> Linking executable
> -----> Initializing Swarmlet
> -----> Starting interactive installation
> =====> Configuration confirmed
> -----> The installation will take a few minutes to complete
> -----> Checking apt-get for upgraded packages
> -----> System up to date, continuing installation
> -----> Installing Docker and Docker Compose
> 2020-09-03 17:02:49 URL:https://get.docker.com/ [13857/13857] -> "-" [1]
> curl: (22) The requested URL returned error: 404 Not Found

**Comment by woudsma** [comment]
Hi, thanks for trying out Swarmlet!
I think this has something to do with the installation of Docker Compose, since that uses `curl`.
https://github.com/swarmlet/swarmlet/blob/015ccda645a70f5cd9ec0a46be29b97d5409cb28/src/lib/functions#L124
I'm not familiar with DietPi, but it would be nice to be able to install Swarmlet on RPI's.
With RPI + Docker I'm not up to date on compatibility. There is some but I've tried it in the past and needed to navigate some issues which I don't remember.
If you fork this repo and find a way to properly install Docker Compose, feel free to open a PR! 🙂 
Let me know if you need help! We have a Slack channel you're welcome to join.

**Comment by TrikkStar** [comment]
Not super familiar with Shell so I'm not sure I could make a useful PR.
Some notes from further testing:

- Installed docker-compose via `apt` and got passed my initial error
-  Next issue I found was that I had to manually create `/.ssh/authorized_keys` as I got an error about the file not existing, might want to add a check to see if the file exists before you `cat` it
- I received the following message when installing with the creation of a Swap Partition `fallocate: fallocate failed: Text file busy`. Looking into this you get this error if you already have a swapfile and try to incorrectly create a new one. Might want to add a check to ensure that there isn't a existing swapfile before attempting to create one.
- Trying with swapfile=False I now get an error stating that `adduser: The user `git' already exists.`

**Comment by awojtczyk** [comment]
`nano /etc/hosts`

Remove the ipv6 related entries,  then run following:

```
swarmlet uninstall
docker swarm leave  --force && docker system prune -f -a && service docker restart
BRANCH=master
curl -fsSL https://raw.githubusercontent.com/swarmlet/swarmlet/$BRANCH/install | bash -s \
  INSTALL_BRANCH=$BRANCH \
  INSTALLATION_TYPE=noninteractive \
  INSTALL_ZSH=true \
  NEW_HOSTNAME=name \
  CREATE_SWAP=true \
  INSTALL_MODULES="(swarmpit matomo portainer swarmprom)" \
  SWARMLET_USERNAME=user \
  SWARMLET_PASSWORD=password \
  ROOT_DOMAIN=yourdomain.com
```

**Comment by TrikkStar** [comment]
Following the above gave me the following error:
`Error saving credentials: error storing credentials - err: exit status 1, out: Cannot autolaunch D-Bus without X11 $DISPLAY`

I resolved this by installing the standard unix password manager `pass` following the advice [here](https://anto.online/guides/cannot-autolaunch-d-bus-without-x11-display/)

Now I just need to figure out how to access the modules; as my root domain is behind an existing reverse-proxy, and any requests to specific modules get 404'ed. (I really don't know much at all about web stuff so I'm expecting something to be wrong with my config)

**Comment by woudsma** [comment]
To completely uninstall Swarmlet, you can run `swarmlet uninstall` or `swarmlet nuke`. We still have some work to do on the topic of uninstalling.
This issue seems related, but I'm sure you've seen this one as well: https://github.com/docker/compose/issues/6023
The `Cannot autolaunch D-Bus without X11 $DISPLAY` error is unrelated to Swarmlet itself I assume, it's more likely that your OS has some difficulties with Docker Compose.

**Comment by woudsma** [comment]
Closing this issue as there are no plans to support DietPi (soon)
